import type { Metadata } from 'next';
import './globals.css';
import Header from '../_components/Header/Header';

export const metadata: Metadata = {
  title: 'El Panetario',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
